# Pandas

- Pandas intro
- dataframe & series
- file loading to df
- basic functionalities of pandas
- dataframe with inbuilt data
- accessing data
- loc, iloc method
- drop rows, columns
- sorting, filtering

In [28]:
import pandas as pd
import numpy as np

In [29]:
df = pd.read_csv('student_data.csv')
print(df.head())

  StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0    PH1001       Alif Rahman                  85.0             85.0
1    PH1002     Fatima Akhter                  92.0             92.0
2    PH1003     Imran Hossain                  88.0             88.0
3    PH1004  Jannatul Ferdous                  78.0             78.0
4    PH1005       Kamal Uddin                   NaN              NaN

   Python Marks CompletionStatus EnrollmentDate Instructor    Location
0          88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1           NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2          85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3          82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4          95.0      In Progress     2024-03-05  Mr. Karim  Chattogram

In [31]:
# series means just one column of the dataframe
print(df['StudentID']) # this will return a series

0     PH1001
1     PH1002
2     PH1003
3     PH1004
4     PH1005
5     PH1006
6     PH1007
7     PH1008
8     PH1009
9     PH1010
10    PH1011
11    PH1012
12    PH1013
13    PH1014
14    PH1015
15    PH1016
16    PH1017
17    PH1018
18    PH1019
19    PH1020
Name: StudentID, dtype: object

# different file loading in Pandas

In [2]:
# load csv
import pandas as pd
csv_data = pd.read_csv('student_data.csv')
print(csv_data.head())

  StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0    PH1001       Alif Rahman                  85.0             85.0
1    PH1002     Fatima Akhter                  92.0             92.0
2    PH1003     Imran Hossain                  88.0             88.0
3    PH1004  Jannatul Ferdous                  78.0             78.0
4    PH1005       Kamal Uddin                   NaN              NaN

   Python Marks CompletionStatus EnrollmentDate Instructor    Location
0          88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1           NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2          85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3          82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4          95.0      In Progress     2024-03-05  Mr. Karim  Chattogram

# pandas basic functionalities

In [4]:
print(csv_data)

   StudentID          FullName  Data Structure Marks  Algorithm Marks  \
0     PH1001       Alif Rahman                  85.0             85.0
1     PH1002     Fatima Akhter                  92.0             92.0
2     PH1003     Imran Hossain                  88.0             88.0
3     PH1004  Jannatul Ferdous                  78.0             78.0
4     PH1005       Kamal Uddin                   NaN              NaN
5     PH1006       Laila Begum                  75.0             75.0
6     PH1007    Mahmudul Hasan                  80.0             80.0
7     PH1008       Nadia Islam                  81.0             81.0
8     PH1009        Omar Faruq                  72.0             72.0
9     PH1010      Priya Sharma                  89.0             89.0
10    PH1011      Rahim Sheikh                   NaN              NaN
11    PH1012   Sadia Chowdhury                  85.0             85.0
12    PH1013      Tanvir Ahmed                  75.0             75.0
13    PH1014        Urmi Akter                   NaN              NaN
14    PH1015      Wahiduzzaman                  86.0             86.0
15    PH1016      Ziaur Rahman                  94.0             94.0
16    PH1017       Afsana Mimi                  90.0             90.0
17    PH1018       Babul Ahmed                  88.0             88.0
18    PH1019      Faria Rahman                   NaN              NaN
19    PH1020        Nasir Khan                  86.0             86.0

    Python Marks CompletionStatus EnrollmentDate Instructor    Location
0           88.0        Completed     2024-01-15  Mr. Karim       Dhaka
1            NaN      In Progress     2024-01-20  Ms. Salma  Chattogram
2           85.0        Completed     2024-02-10  Mr. Karim       Dhaka
3           82.0        Completed     2024-02-12  Ms. Salma      Sylhet
4           95.0      In Progress     2024-03-05  Mr. Karim  Chattogram
5           78.0        Completed     2024-03-08  Ms. Salma    Rajshahi
6            NaN      In Progress     2024-04-01  Mr. Karim       Dhaka
7           85.0        Completed     2024-04-22  Ms. Salma  Chattogram
8           76.0        Completed     2024-05-16  Mr. David       Dhaka
9           88.0        Completed     2024-05-20  Ms. Salma      Sylhet
10          91.0      In Progress     2024-06-11  Mr. Karim      Khulna
11          87.0        Completed     2024-06-14  Ms. Salma  Chattogram
12          79.0        Completed     2024-07-02  Mr. David       Dhaka
13           NaN      Not Started     2024-07-09  Ms. Salma    Rajshahi
14          84.0        Completed     2024-08-18  Mr. Karim       Dhaka
15           NaN      In Progress     2024-08-21  Ms. Salma  Chattogram
16          93.0        Completed     2025-09-01  Mr. Karim       Dhaka
17          85.0        Completed     2025-09-05  Ms. Salma      Sylhet
18           NaN      Not Started     2025-09-15  Mr. David  Chattogram
19          89.0        Completed     2025-10-02  Ms. Salma       Dhaka

In [5]:
df = csv_data.copy()
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [6]:
df.head(5)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram

In [7]:
df.tail(3)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [ ]:
df.columns  # this is a attribute

Index(['StudentID', 'FullName', 'Data Structure Marks', 'Algorithm Marks',
       'Python Marks', 'CompletionStatus', 'EnrollmentDate', 'Instructor',
       'Location'],
      dtype='object')

In [10]:
import numpy as np

col = list(df.columns)
print(col)

col = np.array(df.columns)
print(col)

['StudentID', 'FullName', 'Data Structure Marks', 'Algorithm Marks', 'Python Marks', 'CompletionStatus', 'EnrollmentDate', 'Instructor', 'Location']
['StudentID' 'FullName' 'Data Structure Marks' 'Algorithm Marks'
 'Python Marks' 'CompletionStatus' 'EnrollmentDate' 'Instructor'
 'Location']

In [11]:
#index
df.index

RangeIndex(start=0, stop=20, step=1)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 9 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   StudentID             20 non-null     object
 1   FullName              20 non-null     object
 2   Data Structure Marks  16 non-null     float64
 3   Algorithm Marks       16 non-null     float64
 4   Python Marks          15 non-null     float64
 5   CompletionStatus      20 non-null     object
 6   EnrollmentDate        20 non-null     object
 7   Instructor            20 non-null     object
 8   Location              20 non-null     object
dtypes: float64(3), object(6)
memory usage: 1.5+ KB

In [14]:
df.describe()

       Data Structure Marks  Algorithm Marks  Python Marks
count             16.000000        16.000000     15.000000
mean              84.000000        84.000000     85.666667
std                6.501282         6.501282      5.394000
min               72.000000        72.000000     76.000000
25%               79.500000        79.500000     83.000000
50%               85.500000        85.500000     85.000000
75%               88.250000        88.250000     88.500000
max               94.000000        94.000000     95.000000

In [15]:
df.sample(6)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka

# transforming to df from inbuilt dates

In [17]:
my_list = [['Alice', 24], ['Bob', 27], ['Charlie', 22]]

list_df = pd.DataFrame(my_list, columns=["Name","Age"], index=['a', 'b', 'c'])
list_df

      Name  Age
a    Alice   24
b      Bob   27
c  Charlie   22

In [ ]:
my_dict = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [24, 27, 22]}

dict_df = pd.DataFrame(my_dict) # automatically column name will be the key of the dictionary
print(dict_df)

      Name  Age
0    Alice   24
1      Bob   27
2  Charlie   22

In [23]:
my_data = [{'Name': 'Alice', 'Age': 24},
           {'Name': 'Bob', 'Age': 27},
           {'Name': 'Charlie', 'Age': 22}]

data_df = pd.DataFrame(my_data)
data_df

      Name  Age
0    Alice   24
1      Bob   27
2  Charlie   22

# Accessing values of a dataframe

In [24]:
# accessing the column of the dataframe
print(df['StudentID'])

0     PH1001
1     PH1002
2     PH1003
3     PH1004
4     PH1005
5     PH1006
6     PH1007
7     PH1008
8     PH1009
9     PH1010
10    PH1011
11    PH1012
12    PH1013
13    PH1014
14    PH1015
15    PH1016
16    PH1017
17    PH1018
18    PH1019
19    PH1020
Name: StudentID, dtype: object

In [27]:
# accessing the row of the dataframe
# loc and iloc are used to access the row of the dataframe

#loc[row(index), column(features)]
# df.loc[ind_start:ind_end, col_start:col_end]

df.loc[0] # this will return the first row of the dataframe

StudentID                    PH1001
FullName                Alif Rahman
Data Structure Marks           85.0
Algorithm Marks                85.0
Python Marks                   88.0
CompletionStatus          Completed
EnrollmentDate           2024-01-15
Instructor                Mr. Karim
Location                      Dhaka
Name: 0, dtype: object

In [28]:
df.loc[0:3] # this will return the first 3 rows of the dataframe

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet

In [29]:
df.loc[0:2, 'StudentID'] # this will return the first 3 rows of the StudentID column

0    PH1001
1    PH1002
2    PH1003
Name: StudentID, dtype: object

In [30]:
# single column access
df.loc[:, "Python Marks"]

0     88.0
1      NaN
2     85.0
3     82.0
4     95.0
5     78.0
6      NaN
7     85.0
8     76.0
9     88.0
10    91.0
11    87.0
12    79.0
13     NaN
14    84.0
15     NaN
16    93.0
17    85.0
18     NaN
19    89.0
Name: Python Marks, dtype: float64

In [33]:
# multiple column access
df.loc[:, ["Python Marks", "StudentID"]]

    Python Marks StudentID
0           88.0    PH1001
1            NaN    PH1002
2           85.0    PH1003
3           82.0    PH1004
4           95.0    PH1005
5           78.0    PH1006
6            NaN    PH1007
7           85.0    PH1008
8           76.0    PH1009
9           88.0    PH1010
10          91.0    PH1011
11          87.0    PH1012
12          79.0    PH1013
13           NaN    PH1014
14          84.0    PH1015
15           NaN    PH1016
16          93.0    PH1017
17          85.0    PH1018
18           NaN    PH1019
19          89.0    PH1020

# set index and iloc

In [34]:
df.head()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram

In [35]:
df.set_index('StudentID', inplace=True)

In [36]:
df

,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
StudentID,,,,,,,,
PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [37]:
df.loc[0:3]

TypeError: cannot do slice indexing on Index with these indexers [0] of type int

In [38]:
df.iloc[0:3]

,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
StudentID,,,,,,,,
PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka

changing column name

In [39]:
df.rename(columns={'Python Marks': 'Python_Marks'}, inplace=True)

In [40]:
df

,FullName,Data Structure Marks,Algorithm Marks,Python_Marks,CompletionStatus,EnrollmentDate,Instructor,Location
StudentID,,,,,,,,
PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

# Changing values & Iteration

In [41]:
df.head()

,FullName,Data Structure Marks,Algorithm Marks,Python_Marks,CompletionStatus,EnrollmentDate,Instructor,Location
StudentID,,,,,,,,
PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram

In [43]:
df = pd.read_csv('student_data.csv')
df.drop(0, inplace=True) # this will drop the row with index 0

In [44]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka

In [45]:
# drop column
df.drop('Instructor', axis = 1, inplace=True)
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka

In [46]:
# value change

df.loc[1, 'Python Marks'] = 95
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
1,PH1002,Fatima Akhter,92.0,92.0,95.0,In Progress,2024-01-20,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Dhaka

In [ ]:
df.loc[1:3, 'Python Marks']+=4
df.head()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
1,PH1002,Fatima Akhter,92.0,92.0,99.0,In Progress,2024-01-20,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,89.0,Completed,2024-02-10,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,86.0,Completed,2024-02-12,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Chattogram
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Rajshahi

In [52]:
df.loc[:, 'Python Marks']-=5
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
1,PH1002,Fatima Akhter,92.0,92.0,94.0,In Progress,2024-01-20,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,84.0,Completed,2024-02-10,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,81.0,Completed,2024-02-12,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,90.0,In Progress,2024-03-05,Chattogram
5,PH1006,Laila Begum,75.0,75.0,73.0,Completed,2024-03-08,Rajshahi
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
7,PH1008,Nadia Islam,81.0,81.0,80.0,Completed,2024-04-22,Chattogram
8,PH1009,Omar Faruq,72.0,72.0,71.0,Completed,2024-05-16,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,83.0,Completed,2024-05-20,Sylhet
10,PH1011,Rahim Sheikh,NaN,NaN,86.0,In Progress,2024-06-11,Khulna
11,PH1012,Sadia Chowdhury,85.0,85.0,82.0,Completed,2024-06-14,Chattogram
12,PH1013,Tanvir Ahmed,75.0,75.0,74.0,Completed,2024-07-02,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
14,PH1015,Wahiduzzaman,86.0,86.0,79.0,Completed,2024-08-18,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,88.0,Completed,2025-09-01,Dhaka
17,PH1018,Babul Ahmed,88.0,88.0,80.0,Completed,2025-09-05,Sylhet
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram
19,PH1020,Nasir Khan,86.0,86.0,84.0,Completed,2025-10-02,Dhaka

In [53]:
for i, series in df.iterrows():
    print (i, series)

1 StudentID                      PH1002
FullName                Fatima Akhter
Data Structure Marks             92.0
Algorithm Marks                  92.0
Python Marks                     94.0
CompletionStatus          In Progress
EnrollmentDate             2024-01-20
Location                   Chattogram
Name: 1, dtype: object
2 StudentID                      PH1003
FullName                Imran Hossain
Data Structure Marks             88.0
Algorithm Marks                  88.0
Python Marks                     84.0
CompletionStatus            Completed
EnrollmentDate             2024-02-10
Location                        Dhaka
Name: 2, dtype: object
3 StudentID                         PH1004
FullName                Jannatul Ferdous
Data Structure Marks                78.0
Algorithm Marks                     78.0
Python Marks                        81.0
CompletionStatus               Completed
EnrollmentDate                2024-02-12
Location                          Sylhet
Name: 3, dtype: object
4 StudentID                    PH1005
FullName                Kamal Uddin
Data Structure Marks            NaN
Algorithm Marks                 NaN
Python Marks                   90.0
CompletionStatus        In Progress
EnrollmentDate           2024-03-05
Location                 Chattogram
Name: 4, dtype: object
5 StudentID                    PH1006
FullName                Laila Begum
Data Structure Marks           75.0
Algorithm Marks                75.0
Python Marks                   73.0
CompletionStatus          Completed
EnrollmentDate           2024-03-08
Location                   Rajshahi
Name: 5, dtype: object
6 StudentID                       PH1007
FullName                Mahmudul Hasan
Data Structure Marks              80.0
Algorithm Marks                   80.0
Python Marks                       NaN
CompletionStatus           In Progress
EnrollmentDate              2024-04-01
Location                         Dhaka
Name: 6, dtype: object
7 StudentID                    PH1008
FullName                Nadia Islam
Data Structure Marks           81.0
Algorithm Marks                81.0
Python Marks                   80.0
CompletionStatus          Completed
EnrollmentDate           2024-04-22
Location                 Chattogram
Name: 7, dtype: object
8 StudentID                   PH1009
FullName                Omar Faruq
Data Structure Marks          72.0
Algorithm Marks               72.0
Python Marks                  71.0
CompletionStatus         Completed
EnrollmentDate          2024-05-16
Location                     Dhaka
Name: 8, dtype: object
9 StudentID                     PH1010
FullName                Priya Sharma
Data Structure Marks            89.0
Algorithm Marks                 89.0
Python Marks                    83.0
CompletionStatus           Completed
EnrollmentDate            2024-05-20
Location                      Sylhet
Name: 9, dtype: object
10 StudentID                     PH1011
FullName                Rahim Sheikh
Data Structure Marks             NaN
Algorithm Marks                  NaN
Python Marks                    86.0
CompletionStatus         In Progress
EnrollmentDate            2024-06-11
Location                      Khulna
Name: 10, dtype: object
11 StudentID                        PH1012
FullName                Sadia Chowdhury
Data Structure Marks               85.0
Algorithm Marks                    85.0
Python Marks                       82.0
CompletionStatus              Completed
EnrollmentDate               2024-06-14
Location                     Chattogram
Name: 11, dtype: object
12 StudentID                     PH1013
FullName                Tanvir Ahmed
Data Structure Marks            75.0
Algorithm Marks                 75.0
Python Marks                    74.0
CompletionStatus           Completed
EnrollmentDate            2024-07-02
Location                       Dhaka
Name: 12, dtype: object
13 StudentID                    PH1014
FullName                 Urmi Akter
Data Structure Marks            NaN
Algorithm Marks                 NaN
Python Marks                    NaN
CompletionStatus        Not Started
EnrollmentDate           2024-07-09
Location                   Rajshahi
Name: 13, dtype: object
14 StudentID                     PH1015
FullName                Wahiduzzaman
Data Structure Marks            86.0
Algorithm Marks                 86.0
Python Marks                    79.0
CompletionStatus           Completed
EnrollmentDate            2024-08-18
Location                       Dhaka
Name: 14, dtype: object
15 StudentID                     PH1016
FullName                Ziaur Rahman
Data Structure Marks            94.0
Algorithm Marks                 94.0
Python Marks                     NaN
CompletionStatus         In Progress
EnrollmentDate            2024-08-21
Location                  Chattogram
Name: 15, dtype: object
16 StudentID                    PH1017
FullName                Afsana Mimi
Data Structure Marks           90.0
Algorithm Marks                90.0
Python Marks                   88.0
CompletionStatus          Completed
EnrollmentDate           2025-09-01
Location                      Dhaka
Name: 16, dtype: object
17 StudentID                    PH1018
FullName                Babul Ahmed
Data Structure Marks           88.0
Algorithm Marks                88.0
Python Marks                   80.0
CompletionStatus          Completed
EnrollmentDate           2025-09-05
Location                     Sylhet
Name: 17, dtype: object
18 StudentID                     PH1019
FullName                Faria Rahman
Data Structure Marks             NaN
Algorithm Marks                  NaN
Python Marks                     NaN
CompletionStatus         Not Started
EnrollmentDate            2025-09-15
Location                  Chattogram
Name: 18, dtype: object
19 StudentID                   PH1020
FullName                Nasir Khan
Data Structure Marks          86.0
Algorithm Marks               86.0
Python Marks                  84.0
CompletionStatus         Completed
EnrollmentDate          2025-10-02
Location                     Dhaka
Name: 19, dtype: object

In [54]:
for i in df.itertuples():
    print(i)

Pandas(Index=1, StudentID='PH1002', FullName='Fatima Akhter', _3=92.0, _4=92.0, _5=94.0, CompletionStatus='In Progress', EnrollmentDate='2024-01-20', Location='Chattogram')
Pandas(Index=2, StudentID='PH1003', FullName='Imran Hossain', _3=88.0, _4=88.0, _5=84.0, CompletionStatus='Completed', EnrollmentDate='2024-02-10', Location='Dhaka')
Pandas(Index=3, StudentID='PH1004', FullName='Jannatul Ferdous', _3=78.0, _4=78.0, _5=81.0, CompletionStatus='Completed', EnrollmentDate='2024-02-12', Location='Sylhet')
Pandas(Index=4, StudentID='PH1005', FullName='Kamal Uddin', _3=nan, _4=nan, _5=90.0, CompletionStatus='In Progress', EnrollmentDate='2024-03-05', Location='Chattogram')
Pandas(Index=5, StudentID='PH1006', FullName='Laila Begum', _3=75.0, _4=75.0, _5=73.0, CompletionStatus='Completed', EnrollmentDate='2024-03-08', Location='Rajshahi')
Pandas(Index=6, StudentID='PH1007', FullName='Mahmudul Hasan', _3=80.0, _4=80.0, _5=nan, CompletionStatus='In Progress', EnrollmentDate='2024-04-01', Location='Dhaka')
Pandas(Index=7, StudentID='PH1008', FullName='Nadia Islam', _3=81.0, _4=81.0, _5=80.0, CompletionStatus='Completed', EnrollmentDate='2024-04-22', Location='Chattogram')
Pandas(Index=8, StudentID='PH1009', FullName='Omar Faruq', _3=72.0, _4=72.0, _5=71.0, CompletionStatus='Completed', EnrollmentDate='2024-05-16', Location='Dhaka')
Pandas(Index=9, StudentID='PH1010', FullName='Priya Sharma', _3=89.0, _4=89.0, _5=83.0, CompletionStatus='Completed', EnrollmentDate='2024-05-20', Location='Sylhet')
Pandas(Index=10, StudentID='PH1011', FullName='Rahim Sheikh', _3=nan, _4=nan, _5=86.0, CompletionStatus='In Progress', EnrollmentDate='2024-06-11', Location='Khulna')
Pandas(Index=11, StudentID='PH1012', FullName='Sadia Chowdhury', _3=85.0, _4=85.0, _5=82.0, CompletionStatus='Completed', EnrollmentDate='2024-06-14', Location='Chattogram')
Pandas(Index=12, StudentID='PH1013', FullName='Tanvir Ahmed', _3=75.0, _4=75.0, _5=74.0, CompletionStatus='Completed', EnrollmentDate='2024-07-02', Location='Dhaka')
Pandas(Index=13, StudentID='PH1014', FullName='Urmi Akter', _3=nan, _4=nan, _5=nan, CompletionStatus='Not Started', EnrollmentDate='2024-07-09', Location='Rajshahi')
Pandas(Index=14, StudentID='PH1015', FullName='Wahiduzzaman', _3=86.0, _4=86.0, _5=79.0, CompletionStatus='Completed', EnrollmentDate='2024-08-18', Location='Dhaka')
Pandas(Index=15, StudentID='PH1016', FullName='Ziaur Rahman', _3=94.0, _4=94.0, _5=nan, CompletionStatus='In Progress', EnrollmentDate='2024-08-21', Location='Chattogram')
Pandas(Index=16, StudentID='PH1017', FullName='Afsana Mimi', _3=90.0, _4=90.0, _5=88.0, CompletionStatus='Completed', EnrollmentDate='2025-09-01', Location='Dhaka')
Pandas(Index=17, StudentID='PH1018', FullName='Babul Ahmed', _3=88.0, _4=88.0, _5=80.0, CompletionStatus='Completed', EnrollmentDate='2025-09-05', Location='Sylhet')
Pandas(Index=18, StudentID='PH1019', FullName='Faria Rahman', _3=nan, _4=nan, _5=nan, CompletionStatus='Not Started', EnrollmentDate='2025-09-15', Location='Chattogram')
Pandas(Index=19, StudentID='PH1020', FullName='Nasir Khan', _3=86.0, _4=86.0, _5=84.0, CompletionStatus='Completed', EnrollmentDate='2025-10-02', Location='Dhaka')

# sort

In [55]:
df.sort_values(by='Python Marks', ascending=False, inplace=True)
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
1,PH1002,Fatima Akhter,92.0,92.0,94.0,In Progress,2024-01-20,Chattogram
4,PH1005,Kamal Uddin,NaN,NaN,90.0,In Progress,2024-03-05,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,88.0,Completed,2025-09-01,Dhaka
10,PH1011,Rahim Sheikh,NaN,NaN,86.0,In Progress,2024-06-11,Khulna
19,PH1020,Nasir Khan,86.0,86.0,84.0,Completed,2025-10-02,Dhaka
2,PH1003,Imran Hossain,88.0,88.0,84.0,Completed,2024-02-10,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,83.0,Completed,2024-05-20,Sylhet
11,PH1012,Sadia Chowdhury,85.0,85.0,82.0,Completed,2024-06-14,Chattogram
3,PH1004,Jannatul Ferdous,78.0,78.0,81.0,Completed,2024-02-12,Sylhet
7,PH1008,Nadia Islam,81.0,81.0,80.0,Completed,2024-04-22,Chattogram
17,PH1018,Babul Ahmed,88.0,88.0,80.0,Completed,2025-09-05,Sylhet
14,PH1015,Wahiduzzaman,86.0,86.0,79.0,Completed,2024-08-18,Dhaka
12,PH1013,Tanvir Ahmed,75.0,75.0,74.0,Completed,2024-07-02,Dhaka
5,PH1006,Laila Begum,75.0,75.0,73.0,Completed,2024-03-08,Rajshahi
8,PH1009,Omar Faruq,72.0,72.0,71.0,Completed,2024-05-16,Dhaka
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram

In [57]:
copy = df.sort_values(['Python Marks', 'Algorithm Marks'], ascending=[False, True])  # this will sort the dataframe by Python Marks in descending order and if there are multiple rows with the same Python Marks, then it will sort those rows by algorithm Marks in ascending order

In [58]:
copy

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
1,PH1002,Fatima Akhter,92.0,92.0,94.0,In Progress,2024-01-20,Chattogram
4,PH1005,Kamal Uddin,NaN,NaN,90.0,In Progress,2024-03-05,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,88.0,Completed,2025-09-01,Dhaka
10,PH1011,Rahim Sheikh,NaN,NaN,86.0,In Progress,2024-06-11,Khulna
19,PH1020,Nasir Khan,86.0,86.0,84.0,Completed,2025-10-02,Dhaka
2,PH1003,Imran Hossain,88.0,88.0,84.0,Completed,2024-02-10,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,83.0,Completed,2024-05-20,Sylhet
11,PH1012,Sadia Chowdhury,85.0,85.0,82.0,Completed,2024-06-14,Chattogram
3,PH1004,Jannatul Ferdous,78.0,78.0,81.0,Completed,2024-02-12,Sylhet
7,PH1008,Nadia Islam,81.0,81.0,80.0,Completed,2024-04-22,Chattogram
17,PH1018,Babul Ahmed,88.0,88.0,80.0,Completed,2025-09-05,Sylhet
14,PH1015,Wahiduzzaman,86.0,86.0,79.0,Completed,2024-08-18,Dhaka
12,PH1013,Tanvir Ahmed,75.0,75.0,74.0,Completed,2024-07-02,Dhaka
5,PH1006,Laila Begum,75.0,75.0,73.0,Completed,2024-03-08,Rajshahi
8,PH1009,Omar Faruq,72.0,72.0,71.0,Completed,2024-05-16,Dhaka
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram

# Filtering data based on condition

In [59]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
1,PH1002,Fatima Akhter,92.0,92.0,94.0,In Progress,2024-01-20,Chattogram
4,PH1005,Kamal Uddin,NaN,NaN,90.0,In Progress,2024-03-05,Chattogram
16,PH1017,Afsana Mimi,90.0,90.0,88.0,Completed,2025-09-01,Dhaka
10,PH1011,Rahim Sheikh,NaN,NaN,86.0,In Progress,2024-06-11,Khulna
19,PH1020,Nasir Khan,86.0,86.0,84.0,Completed,2025-10-02,Dhaka
2,PH1003,Imran Hossain,88.0,88.0,84.0,Completed,2024-02-10,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,83.0,Completed,2024-05-20,Sylhet
11,PH1012,Sadia Chowdhury,85.0,85.0,82.0,Completed,2024-06-14,Chattogram
3,PH1004,Jannatul Ferdous,78.0,78.0,81.0,Completed,2024-02-12,Sylhet
7,PH1008,Nadia Islam,81.0,81.0,80.0,Completed,2024-04-22,Chattogram
17,PH1018,Babul Ahmed,88.0,88.0,80.0,Completed,2025-09-05,Sylhet
14,PH1015,Wahiduzzaman,86.0,86.0,79.0,Completed,2024-08-18,Dhaka
12,PH1013,Tanvir Ahmed,75.0,75.0,74.0,Completed,2024-07-02,Dhaka
5,PH1006,Laila Begum,75.0,75.0,73.0,Completed,2024-03-08,Rajshahi
8,PH1009,Omar Faruq,72.0,72.0,71.0,Completed,2024-05-16,Dhaka
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Dhaka
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Chattogram
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram

In [60]:
not_started =df.loc[df['CompletionStatus']=='Not Started']
not_started

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Rajshahi
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Chattogram

In [61]:
completed = df.loc[df['CompletionStatus']=='Completed']

completed

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
16,PH1017,Afsana Mimi,90.0,90.0,88.0,Completed,2025-09-01,Dhaka
19,PH1020,Nasir Khan,86.0,86.0,84.0,Completed,2025-10-02,Dhaka
2,PH1003,Imran Hossain,88.0,88.0,84.0,Completed,2024-02-10,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,83.0,Completed,2024-05-20,Sylhet
11,PH1012,Sadia Chowdhury,85.0,85.0,82.0,Completed,2024-06-14,Chattogram
3,PH1004,Jannatul Ferdous,78.0,78.0,81.0,Completed,2024-02-12,Sylhet
7,PH1008,Nadia Islam,81.0,81.0,80.0,Completed,2024-04-22,Chattogram
17,PH1018,Babul Ahmed,88.0,88.0,80.0,Completed,2025-09-05,Sylhet
14,PH1015,Wahiduzzaman,86.0,86.0,79.0,Completed,2024-08-18,Dhaka
12,PH1013,Tanvir Ahmed,75.0,75.0,74.0,Completed,2024-07-02,Dhaka
5,PH1006,Laila Begum,75.0,75.0,73.0,Completed,2024-03-08,Rajshahi
8,PH1009,Omar Faruq,72.0,72.0,71.0,Completed,2024-05-16,Dhaka

In [ ]:
completed_and_good = df.loc[(df['CompletionStatus']=='Completed') & (df['Python Marks']>80)]    # two conditions
completed_and_good

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Location
16,PH1017,Afsana Mimi,90.0,90.0,88.0,Completed,2025-09-01,Dhaka
19,PH1020,Nasir Khan,86.0,86.0,84.0,Completed,2025-10-02,Dhaka
2,PH1003,Imran Hossain,88.0,88.0,84.0,Completed,2024-02-10,Dhaka
9,PH1010,Priya Sharma,89.0,89.0,83.0,Completed,2024-05-20,Sylhet
11,PH1012,Sadia Chowdhury,85.0,85.0,82.0,Completed,2024-06-14,Chattogram
3,PH1004,Jannatul Ferdous,78.0,78.0,81.0,Completed,2024-02-12,Sylhet