# filtering on string

In [82]:
import pandas as pd

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eve", "Frank", "Grace", "Hannah","Sakib"],
    "City": ["New York", "Los Angeles", "Newark", "Boston", "New Delhi", "Chicago", "New Orleans", "Houston","H Los Ang"],
    "Department": ["HR", "IT", "Finance", "IT", "HR", "Marketing", "Finance", "HR", "HR"],
    "Salary": [50000, 60000, 55000, 70000, 52000, 58000, 62000, 51000,70000]
}

df = pd.DataFrame(data)

In [83]:
df

      Name         City Department  Salary
0    Alice     New York         HR   50000
1      Bob  Los Angeles         IT   60000
2  Charlie       Newark    Finance   55000
3    David       Boston         IT   70000
4      Eve    New Delhi         HR   52000
5    Frank      Chicago  Marketing   58000
6    Grace  New Orleans    Finance   62000
7   Hannah      Houston         HR   51000
8    Sakib    H Los Ang         HR   70000

In [84]:
df.loc[df["City"].str.contains("New",case=False)]

      Name         City Department  Salary
0    Alice     New York         HR   50000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000

```python

the r before the string (r"^Los") means “raw string” in Python.

🔹 What is a raw string?

A raw string tells Python:

“Treat everything inside this string exactly as it is — don’t interpret special escape characters.”

In [85]:
# starts with Los

df.loc[df["City"].str.contains(r"^Los")]

  Name         City Department  Salary
1  Bob  Los Angeles         IT   60000

In [86]:
# ends with rk

df.loc[df["City"].str.contains(r"rk$")]

      Name      City Department  Salary
0    Alice  New York         HR   50000
2  Charlie    Newark    Finance   55000

In [87]:
# name starts with a vouel

df.loc[df["Name"].str.contains(r"^[AEIOUaeiou]")]

    Name       City Department  Salary
0  Alice   New York         HR   50000
4    Eve  New Delhi         HR   52000

In [88]:
# cities contains "Los" or "New"

df.loc[df["City"].str.contains(r"Los|New")]

      Name         City Department  Salary
0    Alice     New York         HR   50000
1      Bob  Los Angeles         IT   60000
2  Charlie       Newark    Finance   55000
4      Eve    New Delhi         HR   52000
6    Grace  New Orleans    Finance   62000
8    Sakib    H Los Ang         HR   70000

# Adding new columns

In [89]:
df = pd.read_csv("E:\Phitron_AI_ML\Phitron-AI-ML\Week03\student_data.csv")

<>:1: SyntaxWarning: invalid escape sequence '\P'
<>:1: SyntaxWarning: invalid escape sequence '\P'
C:\Users\User\AppData\Local\Temp\ipykernel_4340\849076452.py:1: SyntaxWarning: invalid escape sequence '\P'
  df = pd.read_csv("E:\Phitron_AI_ML\Phitron-AI-ML\Week03\student_data.csv")

In [90]:
df.head()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram

In [91]:
# adding a column with constant value

df["Country"] = "Bangladesh"
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh

In [92]:
df["total_marks"] = df["Data Structure Marks"] + df["Algorithm Marks"] + df["Python Marks"]

In [93]:
df.head()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,total_marks
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,NaN
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN

In [94]:
df["Grade_DS"] = df["Data Structure Marks"].apply(lambda x: "A+" if x>=80 else "other")

In [95]:
df.head()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,total_marks,Grade_DS
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A+
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,NaN,A+
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A+
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,other
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN,other

In [96]:
import numpy as np
df["Grade_DS"] = np.where(df["Data Structure Marks"]>=80, "A+", "other")

In [97]:
df.head()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,total_marks,Grade_DS
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A+
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,NaN,A+
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A+
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,other
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN,other

In [98]:
df["Passed in DS"] = df["Data Structure Marks"]>40
df.head()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,total_marks,Grade_DS,Passed in DS
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A+,True
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A+,True
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,other,True
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN,other,False

In [99]:
df["First Name"] = df["FullName"].str.split(" ").str[0]
df.head()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,total_marks,Grade_DS,Passed in DS,First Name
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A+,True,Alif
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True,Fatima
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A+,True,Imran
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,other,True,Jannatul
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN,other,False,Kamal

In [100]:
df.to_csv("E:/Phitron_AI_ML/Phitron-AI-ML/Week04/student_data_modified.csv", index=False)

# Unique and Null Checking

In [101]:
import pandas as pd
data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "David", "Bob"],
    "City": ["New York", "London", "Paris", "New York", "Tokyo", "London"],
    "Score": [85, 90, 78, 85, 95, 90]
}

df = pd.DataFrame(data)
df

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     85
4    David     Tokyo     95
5      Bob    London     90

In [102]:
df["Name"].unique()

array(['Alice', 'Bob', 'Charlie', 'David'], dtype=object)

In [103]:
df["Name"].isnull()

0    False
1    False
2    False
3    False
4    False
5    False
Name: Name, dtype: bool

In [104]:
df["Name"].nunique()    # number of unique values in the column

4

In [105]:
df.nunique()    # number of unique values in each column

Name     4
City     4
Score    4
dtype: int64

In [106]:
df.isnull()

    Name   City  Score
0  False  False  False
1  False  False  False
2  False  False  False
3  False  False  False
4  False  False  False
5  False  False  False

In [107]:
df.isnull().sum()    # number of null values in each column

Name     0
City     0
Score    0
dtype: int64

In [108]:
df.notnull()

   Name  City  Score
0  True  True   True
1  True  True   True
2  True  True   True
3  True  True   True
4  True  True   True
5  True  True   True

In [109]:
df["City"].hasnans      # check if there are any null values in the column

False

# Handling duplicate values

In [110]:
import pandas as pd
data = {
    "Name": ["Alice", "Bob", "Charlie", "Alice", "David", "Bob"],
    "City": ["New York", "London", "Paris", "New York", "Tokyo", "London"],
    "Score": [85, 90, 78, 70, 95, 90]
}

df = pd.DataFrame(data)
df

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95
5      Bob    London     90

In [111]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
dtype: bool

In [112]:
df.duplicated().sum()    # number of duplicate rows

np.int64(1)

In [113]:
df.drop_duplicates(inplace=True)
df

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
3    Alice  New York     70
4    David     Tokyo     95

In [114]:
# to delete column wise duplicates

# based on name

df.drop_duplicates(subset=["Name"], inplace=True)
df

      Name      City  Score
0    Alice  New York     85
1      Bob    London     90
2  Charlie     Paris     78
4    David     Tokyo     95

In [115]:
df.drop_duplicates(subset=["Name"], keep="last", inplace=True) # to keep the last occurrence of the duplicate value in the "Name" column and delete the rest

# Handling Null values

In [116]:
df = pd.read_csv("student_data_modified.csv")

In [117]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,total_marks,Grade_DS,Passed in DS,First Name
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A+,True,Alif
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True,Fatima
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A+,True,Imran
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,other,True,Jannatul
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN,other,False,Kamal
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,other,True,Laila
6,PH1007,Mahmudul Hasan,80.0,80.0,NaN,In Progress,2024-04-01,Mr. Karim,Dhaka,Bangladesh,NaN,A+,True,Mahmudul
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A+,True,Nadia
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,other,True,Omar
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A+,True,Priya
10,PH1011,Rahim Sheikh,NaN,NaN,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,NaN,other,False,Rahim
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A+,True,Sadia
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,other,True,Tanvir
13,PH1014,Urmi Akter,NaN,NaN,NaN,Not Started,2024-07-09,Ms. Salma,Rajshahi,Bangladesh,NaN,other,False,Urmi
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A+,True,Wahiduzzaman
15,PH1016,Ziaur Rahman,94.0,94.0,NaN,In Progress,2024-08-21,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True,Ziaur
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A+,True,Afsana
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A+,True,Babul
18,PH1019,Faria Rahman,NaN,NaN,NaN,Not Started,2025-09-15,Mr. David,Chattogram,Bangladesh,NaN,other,False,Faria
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A+,True,Nasir

In [118]:
df2 = df.copy()

In [119]:
df.dropna(inplace=True) # row te kono ghor e null value thakle sei row ta purota delete hoye jabe

In [120]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,total_marks,Grade_DS,Passed in DS,First Name
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A+,True,Alif
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A+,True,Imran
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,other,True,Jannatul
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,other,True,Laila
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A+,True,Nadia
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,other,True,Omar
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A+,True,Priya
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A+,True,Sadia
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,other,True,Tanvir
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A+,True,Wahiduzzaman
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A+,True,Afsana
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A+,True,Babul
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A+,True,Nasir

In [121]:
df2.dropna(how="all", inplace=True) # row te jodi purota ghor e null value thake tahole sei row ta delete hoye jabe

In [122]:
df2.head(5)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,total_marks,Grade_DS,Passed in DS,First Name
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A+,True,Alif
1,PH1002,Fatima Akhter,92.0,92.0,NaN,In Progress,2024-01-20,Ms. Salma,Chattogram,Bangladesh,NaN,A+,True,Fatima
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A+,True,Imran
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,other,True,Jannatul
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN,other,False,Kamal

In [123]:
# drop when python marks is null

df2.dropna(subset=["Python Marks"], inplace=True)
df2.head(5)

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,total_marks,Grade_DS,Passed in DS,First Name
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A+,True,Alif
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A+,True,Imran
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,other,True,Jannatul
4,PH1005,Kamal Uddin,NaN,NaN,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,NaN,other,False,Kamal
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,other,True,Laila

In [124]:
df2.fillna(0) # null value gulo ke 0 diye fill kore dibe

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,total_marks,Grade_DS,Passed in DS,First Name
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A+,True,Alif
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A+,True,Imran
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,other,True,Jannatul
4,PH1005,Kamal Uddin,0.0,0.0,95.0,In Progress,2024-03-05,Mr. Karim,Chattogram,Bangladesh,0.0,other,False,Kamal
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,other,True,Laila
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A+,True,Nadia
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,other,True,Omar
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A+,True,Priya
10,PH1011,Rahim Sheikh,0.0,0.0,91.0,In Progress,2024-06-11,Mr. Karim,Khulna,Bangladesh,0.0,other,False,Rahim
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A+,True,Sadia
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,other,True,Tanvir
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A+,True,Wahiduzzaman
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A+,True,Afsana
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A+,True,Babul
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A+,True,Nasir

In [125]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,total_marks,Grade_DS,Passed in DS,First Name
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A+,True,Alif
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A+,True,Imran
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,other,True,Jannatul
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,other,True,Laila
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A+,True,Nadia
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,other,True,Omar
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A+,True,Priya
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A+,True,Sadia
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,other,True,Tanvir
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A+,True,Wahiduzzaman
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A+,True,Afsana
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A+,True,Babul
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A+,True,Nasir

In [126]:
df["Python Marks"].fillna(df["Python Marks"].mean())

0     88.0
2     85.0
3     82.0
5     78.0
7     85.0
8     76.0
9     88.0
11    87.0
12    79.0
14    84.0
16    93.0
17    85.0
19    89.0
Name: Python Marks, dtype: float64

# statistical functions in pandas

In [127]:
df.dropna(inplace=True)

In [128]:
df.head()

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,total_marks,Grade_DS,Passed in DS,First Name
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A+,True,Alif
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A+,True,Imran
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,other,True,Jannatul
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,other,True,Laila
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A+,True,Nadia

In [129]:
df["Data Structure Marks"].sum()

np.float64(1078.0)

In [130]:
df["Data Structure Marks"].mean()

np.float64(82.92307692307692)

In [131]:
df["Data Structure Marks"].min()

np.float64(72.0)

In [132]:
df["Data Structure Marks"].max()

np.float64(90.0)

In [133]:
df["Data Structure Marks"].median()

np.float64(85.0)

In [134]:
df["Data Structure Marks"].mode()

0    75.0
1    85.0
2    86.0
3    88.0
Name: Data Structure Marks, dtype: float64

In [135]:
# correlation matrix

df[["Data Structure Marks", "Algorithm Marks", "Python Marks"]].corr()

                      Data Structure Marks  Algorithm Marks  Python Marks
Data Structure Marks              1.000000         1.000000      0.893455
Algorithm Marks                   1.000000         1.000000      0.893455
Python Marks                      0.893455         0.893455      1.000000

In [136]:
# sum in diff columns (column wise sum)

df[["Data Structure Marks", "Algorithm Marks", "Python Marks"]].sum()

Data Structure Marks    1078.0
Algorithm Marks         1078.0
Python Marks            1099.0
dtype: float64

In [137]:
# sum in diff columns (row wise sum)

df[["Data Structure Marks", "Algorithm Marks", "Python Marks"]].sum(axis=1)

0     258.0
2     261.0
3     238.0
5     228.0
7     247.0
8     220.0
9     266.0
11    257.0
12    229.0
14    256.0
16    273.0
17    261.0
19    261.0
dtype: float64

In [138]:
df['total_marks'] = df.iloc[:, 2:5].sum(axis=1)

In [139]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,total_marks,Grade_DS,Passed in DS,First Name
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A+,True,Alif
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A+,True,Imran
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,other,True,Jannatul
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,other,True,Laila
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A+,True,Nadia
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,other,True,Omar
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A+,True,Priya
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A+,True,Sadia
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,other,True,Tanvir
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A+,True,Wahiduzzaman
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A+,True,Afsana
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A+,True,Babul
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A+,True,Nasir

In [140]:
df.describe()

       Data Structure Marks  Algorithm Marks  Python Marks  total_marks
count             13.000000        13.000000     13.000000    13.000000
mean              82.923077        82.923077     84.538462   250.384615
std                6.047886         6.047886      4.789144    16.515339
min               72.000000        72.000000     76.000000   220.000000
25%               78.000000        78.000000     82.000000   238.000000
50%               85.000000        85.000000     85.000000   257.000000
75%               88.000000        88.000000     88.000000   261.000000
max               90.000000        90.000000     93.000000   273.000000

# Apply Function on DF

In [141]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,total_marks,Grade_DS,Passed in DS,First Name
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A+,True,Alif
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A+,True,Imran
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,other,True,Jannatul
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,other,True,Laila
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A+,True,Nadia
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,other,True,Omar
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A+,True,Priya
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A+,True,Sadia
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,other,True,Tanvir
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A+,True,Wahiduzzaman
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A+,True,Afsana
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A+,True,Babul
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A+,True,Nasir

In [142]:
# min max scaling

min_val = df['total_marks'].min()
max_val = df['total_marks'].max()
df['total_marks_scaled'] = df['total_marks'].apply(lambda x: (x - min_val)/(max_val - min_val))

In [143]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,total_marks,Grade_DS,Passed in DS,First Name,total_marks_scaled
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A+,True,Alif,0.716981
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A+,True,Imran,0.773585
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,other,True,Jannatul,0.339623
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,other,True,Laila,0.150943
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A+,True,Nadia,0.509434
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,other,True,Omar,0.000000
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A+,True,Priya,0.867925
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A+,True,Sadia,0.698113
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,other,True,Tanvir,0.169811
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A+,True,Wahiduzzaman,0.679245
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A+,True,Afsana,1.000000
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A+,True,Babul,0.773585
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A+,True,Nasir,0.773585

In [144]:
def grading_system(x):
    if x >= 250:
        return 'A'
    elif x >= 200:
        return 'B'
    elif x >= 150:
        return 'C'
    else:
        return 'D'

df['Grade'] = df['total_marks'].apply(grading_system)

In [145]:
df

,StudentID,FullName,Data Structure Marks,Algorithm Marks,Python Marks,CompletionStatus,EnrollmentDate,Instructor,Location,Country,total_marks,Grade_DS,Passed in DS,First Name,total_marks_scaled,Grade
0,PH1001,Alif Rahman,85.0,85.0,88.0,Completed,2024-01-15,Mr. Karim,Dhaka,Bangladesh,258.0,A+,True,Alif,0.716981,A
2,PH1003,Imran Hossain,88.0,88.0,85.0,Completed,2024-02-10,Mr. Karim,Dhaka,Bangladesh,261.0,A+,True,Imran,0.773585,A
3,PH1004,Jannatul Ferdous,78.0,78.0,82.0,Completed,2024-02-12,Ms. Salma,Sylhet,Bangladesh,238.0,other,True,Jannatul,0.339623,B
5,PH1006,Laila Begum,75.0,75.0,78.0,Completed,2024-03-08,Ms. Salma,Rajshahi,Bangladesh,228.0,other,True,Laila,0.150943,B
7,PH1008,Nadia Islam,81.0,81.0,85.0,Completed,2024-04-22,Ms. Salma,Chattogram,Bangladesh,247.0,A+,True,Nadia,0.509434,B
8,PH1009,Omar Faruq,72.0,72.0,76.0,Completed,2024-05-16,Mr. David,Dhaka,Bangladesh,220.0,other,True,Omar,0.000000,B
9,PH1010,Priya Sharma,89.0,89.0,88.0,Completed,2024-05-20,Ms. Salma,Sylhet,Bangladesh,266.0,A+,True,Priya,0.867925,A
11,PH1012,Sadia Chowdhury,85.0,85.0,87.0,Completed,2024-06-14,Ms. Salma,Chattogram,Bangladesh,257.0,A+,True,Sadia,0.698113,A
12,PH1013,Tanvir Ahmed,75.0,75.0,79.0,Completed,2024-07-02,Mr. David,Dhaka,Bangladesh,229.0,other,True,Tanvir,0.169811,B
14,PH1015,Wahiduzzaman,86.0,86.0,84.0,Completed,2024-08-18,Mr. Karim,Dhaka,Bangladesh,256.0,A+,True,Wahiduzzaman,0.679245,A
16,PH1017,Afsana Mimi,90.0,90.0,93.0,Completed,2025-09-01,Mr. Karim,Dhaka,Bangladesh,273.0,A+,True,Afsana,1.000000,A
17,PH1018,Babul Ahmed,88.0,88.0,85.0,Completed,2025-09-05,Ms. Salma,Sylhet,Bangladesh,261.0,A+,True,Babul,0.773585,A
19,PH1020,Nasir Khan,86.0,86.0,89.0,Completed,2025-10-02,Ms. Salma,Dhaka,Bangladesh,261.0,A+,True,Nasir,0.773585,A

In [146]:
def marking_system(df):
    a = df['Data Structure Marks'] *2
    b = df['Algorithm Marks'] * 3
    c = df['Python Marks'] * 4
    return a+b+c

df['total_marks_weighted'] = df.apply(marking_system, axis=1)

# Date Time

In [147]:
df = pd.read_csv("student_completed_data.csv")
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253

In [148]:
df['EnrollmentDate']

0     2024-09-01
1     2024-08-11
2     2024-05-08
3     2024-07-05
4     2024-02-01
5     2024-09-07
6     2024-06-07
7     2024-03-22
8     2024-02-12
9     2024-06-19
10    2024-03-14
11    2024-08-04
12    2024-06-07
13    2024-01-04
14    2024-02-22
15    2024-03-23
16    2024-01-18
17    2024-06-23
18    2024-04-19
19    2024-07-21
Name: EnrollmentDate, dtype: object

In [149]:
print(df['EnrollmentDate'].dtype)

object

In [150]:
df['EnrollmentDate'] = pd.to_datetime(df['EnrollmentDate'])
print(df['EnrollmentDate'].dtype)

datetime64[ns]

In [151]:
df['EnrollmentDate']

0    2024-09-01
1    2024-08-11
2    2024-05-08
3    2024-07-05
4    2024-02-01
5    2024-09-07
6    2024-06-07
7    2024-03-22
8    2024-02-12
9    2024-06-19
10   2024-03-14
11   2024-08-04
12   2024-06-07
13   2024-01-04
14   2024-02-22
15   2024-03-23
16   2024-01-18
17   2024-06-23
18   2024-04-19
19   2024-07-21
Name: EnrollmentDate, dtype: datetime64[ns]

In [152]:
df['EnrollmentYear'] = df['EnrollmentDate'].dt.year
df['EnrollmentMonth'] = df['EnrollmentDate'].dt.month
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,EnrollmentYear,EnrollmentMonth
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300,2024,9
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271,2024,8
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269,2024,5
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270,2024,7
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254,2024,2
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272,2024,9
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249,2024,6
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246,2024,3
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291,2024,2
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286,2024,6
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283,2024,3
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266,2024,8
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248,2024,6
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285,2024,1
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291,2024,2
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234,2024,3
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236,2024,1
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278,2024,6
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277,2024,4
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253,2024,7

In [153]:
df['FinishedDate'] = pd.to_datetime(df['FinishedDate'])
df['Time Duration'] =  df['FinishedDate'] - df['EnrollmentDate']
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks,EnrollmentYear,EnrollmentMonth,Time Duration
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,300,2024,9,113 days
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271,2024,8,88 days
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269,2024,5,92 days
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270,2024,7,80 days
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254,2024,2,76 days
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272,2024,9,115 days
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249,2024,6,43 days
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246,2024,3,40 days
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291,2024,2,117 days
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286,2024,6,61 days
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283,2024,3,89 days
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,266,2024,8,82 days
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248,2024,6,57 days
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285,2024,1,79 days
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291,2024,2,84 days
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234,2024,3,90 days
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,236,2024,1,58 days
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278,2024,6,89 days
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277,2024,4,120 days
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253,2024,7,82 days

# groupby in pandas

In [155]:
df = pd.read_csv("student_completed_data.csv")

In [157]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   StudentID         20 non-null     object
 1   FullName          20 non-null     object
 2   CompletionStatus  20 non-null     object
 3   EnrollmentDate    20 non-null     object
 4   FinishedDate      20 non-null     object
 5   Instructor        20 non-null     object
 6   Location          20 non-null     object
 7   Total Marks       20 non-null     int64
dtypes: int64(1), object(7)
memory usage: 1.4+ KB

In [158]:
import numpy as np

df.loc[df['FullName'] == 'Afsana Mimi', 'Total Marks'] = np.nan
df.loc[df['FullName'] == 'Sadia Chowdhury', 'Total Marks'] = np.nan
df.loc[df['FullName'] == 'Alif Rahman', 'Total Marks'] = np.nan

In [159]:
instructor_group = df.groupby("Instructor")
instructor_group

In [161]:
for name, group in instructor_group:
    print(name)
    display(group)

Mr. David

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254.0
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272.0
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249.0
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286.0
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248.0
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285.0
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291.0
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,NaN
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278.0

Mr. Karim

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271.0
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270.0
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291.0
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283.0
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,NaN
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277.0
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253.0

Ms. Salma

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,NaN
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269.0
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246.0
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234.0

In [162]:
instructor_group.min()

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Location,Total Marks
Instructor,,,,,,,
Mr. David,PH0005,Afsana Mimi,Completed,2024-01-04,2024-03-16,Chattogram,248.0
Mr. Karim,PH0002,Faria Rahman,Completed,2024-02-12,2024-06-08,Dhaka,253.0
Ms. Salma,PH0001,Alif Rahman,Completed,2024-03-22,2024-05-01,Dhaka,234.0

In [163]:
instructor_group.describe()

           Total Marks                                                       \
                 count        mean        std    min     25%    50%     75%
Instructor
Mr. David          8.0  270.375000  17.606310  248.0  252.75  275.0  285.25
Mr. Karim          6.0  274.166667  12.998718  253.0  270.25  274.0  281.50
Ms. Salma          3.0  249.666667  17.785762  234.0  240.00  246.0  257.50


              max
Instructor
Mr. David   291.0
Mr. Karim   291.0
Ms. Salma   269.0

In [166]:
instructor_group.get_group("Mr. David")

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254.0
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272.0
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249.0
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286.0
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248.0
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285.0
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291.0
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,NaN
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278.0

In [169]:
mean_marks = instructor_group['Total Marks'].mean()

In [170]:
df['Total Marks']=df["Total Marks"].fillna(df["Instructor"].map(mean_marks))

In [171]:
df

,StudentID,FullName,CompletionStatus,EnrollmentDate,FinishedDate,Instructor,Location,Total Marks
0,PH0001,Alif Rahman,Completed,2024-09-01,2024-12-23,Ms. Salma,Khulna,249.666667
1,PH0002,Fatima Akhter,Completed,2024-08-11,2024-11-07,Mr. Karim,Dhaka,271.000000
2,PH0003,Imran Hossain,Completed,2024-05-08,2024-08-08,Ms. Salma,Dhaka,269.000000
3,PH0004,Jannatul Ferdous,Completed,2024-07-05,2024-09-23,Mr. Karim,Khulna,270.000000
4,PH0005,Kamal Uddin,Completed,2024-02-01,2024-04-17,Mr. David,Sylhet,254.000000
5,PH0006,Laila Begum,Completed,2024-09-07,2024-12-31,Mr. David,Khulna,272.000000
6,PH0007,Mahmudul Hasan,Completed,2024-06-07,2024-07-20,Mr. David,Chattogram,249.000000
7,PH0008,Nadia Islam,Completed,2024-03-22,2024-05-01,Ms. Salma,Khulna,246.000000
8,PH0009,Omar Faruq,Completed,2024-02-12,2024-06-08,Mr. Karim,Dhaka,291.000000
9,PH0010,Priya Sharma,Completed,2024-06-19,2024-08-19,Mr. David,Dhaka,286.000000
10,PH0011,Rahim Sheikh,Completed,2024-03-14,2024-06-11,Mr. Karim,Sylhet,283.000000
11,PH0012,Sadia Chowdhury,Completed,2024-08-04,2024-10-25,Mr. Karim,Sylhet,274.166667
12,PH0013,Tanvir Ahmed,Completed,2024-06-07,2024-08-03,Mr. David,Dhaka,248.000000
13,PH0014,Urmi Akter,Completed,2024-01-04,2024-03-23,Mr. David,Sylhet,285.000000
14,PH0015,Wahiduzzaman,Completed,2024-02-22,2024-05-16,Mr. David,Rajshahi,291.000000
15,PH0016,Ziaur Rahman,Completed,2024-03-23,2024-06-21,Ms. Salma,Rajshahi,234.000000
16,PH0017,Afsana Mimi,Completed,2024-01-18,2024-03-16,Mr. David,Khulna,270.375000
17,PH0018,Babul Ahmed,Completed,2024-06-23,2024-09-20,Mr. David,Dhaka,278.000000
18,PH0019,Faria Rahman,Completed,2024-04-19,2024-08-17,Mr. Karim,Sylhet,277.000000
19,PH0020,Tariq Hasan,Completed,2024-07-21,2024-10-11,Mr. Karim,Khulna,253.000000