# Pandas

In [3]:


import pandas as pd
import numpy as np

In [4]:
#numpy array

arr = np.array( [ [1,2] , [3,4]] )

In [6]:
df = pd.DataFrame(arr, columns=["A","B"])
df

   A  B
0  1  2
1  3  4

- Series হলো pandas-এর একটি one-dimensional (1D) data structure।
- DataFrame = multiple Series together

In [8]:
s = pd.Series([1,2,3,4,5], index = ["a","b","c","d","e"])
s

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [9]:
for indx, in s.index:
    print(indx)

for indx,val in s.items():
    print(indx,val)

a
b
c
d
e
a 1
b 2
c 3
d 4
e 5

In [10]:
s = s + 10
s

a    11
b    12
c    13
d    14
e    15
dtype: int64

In [11]:
df = pd.DataFrame(
    {
        "Name" : ["Preta", "Alex", "John"],
        "Age" : [20, 21, 19],
        "City" : ["Dhaka", "Chittagong", "Khulna"]
    }
)


df

    Name  Age        City
0  Preta   20       Dhaka
1   Alex   21  Chittagong
2   John   19      Khulna

In [12]:
df1 = pd.Series([1,2], index = ["a","b"])
df2 = pd.Series([3,4], index = ["a","b"])
df3 = df1 + df2

In [13]:
df3

a    4
b    6
dtype: int64

# CSV file

In [17]:
import kagglehub

# Download latest version
path = kagglehub.dataset_download("spscientist/students-performance-in-exams")

print("Path to dataset files:", path)

Downloading to C:\Users\User\.cache\kagglehub\datasets\spscientist\students-performance-in-exams\1.archive...

100%|██████████| 8.70k/8.70k [00:00<?, ?B/s]

Extracting files...
Path to dataset files: C:\Users\User\.cache\kagglehub\datasets\spscientist\students-performance-in-exams\versions\1

In [25]:
df = pd.read_csv(r"C:\Users\User\.cache\kagglehub\datasets\spscientist\students-performance-in-exams\versions\1\StudentsPerformance.csv")

In [26]:
df.head(5)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75

# loc and iloc

In [30]:
df1 = pd.DataFrame(
    {
        "Name" : ["Preta", "Alex", "BOB"],
        "Age" : [20,45,23]
    }, index = ["1","2","3"]
)

In [32]:
df1

    Name  Age
1  Preta   20
2   Alex   45
3    BOB   23

In [35]:
df1["Name"][0]

C:\Users\User\AppData\Local\Temp\ipykernel_10736\2764409328.py:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  df1["Name"][0]

'Preta'

In [37]:
df1.iloc[0,0]

'Preta'

1. loc (label-based)
2. iloc (index-based)

In [43]:
# get multiple rows

df1.loc[['1']]

    Name  Age
1  Preta   20

In [44]:
# add column
df1["Marks"] = [90, 80, 85]
df1

    Name  Age  Marks
1  Preta   20     90
2   Alex   45     80
3    BOB   23     85

- axis = 0	column-wise (উপরে-নিচে)
- axis = 1	row-wise (বাম-ডানে)

In [46]:
# drop column
df1.drop("Marks", axis=1)

    Name  Age
1  Preta   20
2   Alex   45
3    BOB   23

In [47]:
df = pd.DataFrame(
    {
        "Name" : ["Preta", "Alex", "BOB"],
        "Age" : [20,45,23]
    }, index = ["1","2","3"]
)

In [48]:
df.sort_values(by = "Age", ascending=False)

    Name  Age
2   Alex   45
3    BOB   23
1  Preta   20

In [53]:
for indx, row in df.iterrows():
    print(row["Age"])

20
45
23


# Vectorization

In [54]:
df = pd.DataFrame(
    {
        "Marks": [90, 80, 85]
    }
)

In [56]:
df["Marks"] = df["Marks"] + 10
df

   Marks
0    100
1     90
2     95

# Mini Project

In [57]:

data = {
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [85, 67, 90, 45, 88]
}

df = pd.DataFrame(data)
df

      Name  Age  Marks
0    Alice   20     85
1      Bob   21     67
2  Charlie   19     90
3    David   22     45
4      Eva   20     88

In [58]:
# adding grade column
def assign_grade(marks):
    if marks>=80:
        return "A"
    elif marks>=70:
        return "B"
    elif marks>=60:
        return "C"
    elif marks>=50:
        return "D"
    else:
        return "F"
    
df["Grade"] = df["Marks"].apply(assign_grade)

In [59]:
df

      Name  Age  Marks Grade
0    Alice   20     85     A
1      Bob   21     67     C
2  Charlie   19     90     A
3    David   22     45     F
4      Eva   20     88     A

In [60]:
# filtering
top_st = df[df["Marks"]>= 80]
top_st

      Name  Age  Marks Grade
0    Alice   20     85     A
2  Charlie   19     90     A
4      Eva   20     88     A

In [61]:
# sorting
sorted_df = df.sort_values(by= "Marks", ascending= False)
sorted_df

      Name  Age  Marks Grade
2  Charlie   19     90     A
4      Eva   20     88     A
0    Alice   20     85     A
1      Bob   21     67     C
3    David   22     45     F

In [62]:
avg_marks = df["Marks"].mean()

In [63]:
sales_data = {
    "Order_ID": [1, 2, 3, 4, 5, 6, 7, 8],
    "Customer_ID": [101, 102, 101, 103, 104, 102, 105, 101],
    "Product": ["Laptop", "Phone", "Tablet", "Laptop", "Phone", "Tablet", "Laptop", "Phone"],
    "Category": ["Electronics", "Electronics", "Electronics", "Electronics", "Electronics", "Electronics", "Electronics", "Electronics"],
    "Price": [800, 500, 300, 850, 520, 310, 780, 510],
    "Quantity": [1, 2, 1, 1, 1, 3, 1, 2],
    "Date": ["2024-01-05", "2024-01-10", "2024-02-15", "2024-02-20", "2024-03-05", "2024-03-15", "2024-04-01", "2024-04-10"]
}
df = pd.DataFrame(sales_data)
df

   Order_ID  Customer_ID Product     Category  Price  Quantity        Date
0         1          101  Laptop  Electronics    800         1  2024-01-05
1         2          102   Phone  Electronics    500         2  2024-01-10
2         3          101  Tablet  Electronics    300         1  2024-02-15
3         4          103  Laptop  Electronics    850         1  2024-02-20
4         5          104   Phone  Electronics    520         1  2024-03-05
5         6          102  Tablet  Electronics    310         3  2024-03-15
6         7          105  Laptop  Electronics    780         1  2024-04-01
7         8          101   Phone  Electronics    510         2  2024-04-10

In [64]:

df["Date"] = pd.to_datetime(df["Date"])