Create a Pandas Series from the list [10, 20, 30, 40, 50]. Print the Series, its index, and data type. Then create a DataFrame with columns "Name", "Age", and "City" containing at least 4 rows of data.

In [1]:
import pandas as pd
lst = [10, 20, 30, 40, 50]
series = pd.Series(lst)
print(series)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [4]:
print(series.index)
print(type(series))
series.dtype

RangeIndex(start=0, stop=5, step=1)
<class 'pandas.core.series.Series'>

dtype('int64')

In [5]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Age": [20, 21, 19, 22, 20],
    "City": ["Dhaka", "Chittagong", "Khulna", "Sylhet", "Rajshahi"]
})

df

      Name  Age        City
0    Alice   20       Dhaka
1      Bob   21  Chittagong
2  Charlie   19      Khulna
3    David   22      Sylhet
4      Eva   20    Rajshahi

Using any DataFrame, write code to print the number of rows and columns, column data types (.dtypes), and summary statistics (.describe()).

In [8]:
print(len(df.columns))
print(len(df.index))
print(df.dtypes)
df.describe()

3
5
Name    object
Age      int64
City    object
dtype: object

             Age
count   5.000000
mean   20.400000
std     1.140175
min    19.000000
25%    20.000000
50%    20.000000
75%    21.000000
max    22.000000

```python
Create a DataFrame using the dictionary below:


data = {
    'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],
    'Price': [10, 50, 5, 7],
    'Quantity': [100, 60, 200, 150]
}

Print .columns, .index. Access a single column and one full row.

In [14]:
data = {
    'Product': ['Pen', 'Book', 'Eraser', 'Pencil'],
    'Price': [10, 50, 5, 7],
    'Quantity': [100, 60, 200, 150]
}

df = pd.DataFrame(data)
df

  Product  Price  Quantity
0     Pen     10       100
1    Book     50        60
2  Eraser      5       200
3  Pencil      7       150

In [15]:
df.columns

Index(['Product', 'Price', 'Quantity'], dtype='object')

In [12]:
df.index

RangeIndex(start=0, stop=4, step=1)

In [13]:
df.iloc[:, 0]

0       Pen
1      Book
2    Eraser
3    Pencil
Name: Product, dtype: object

```python
# Problem: 
Using .loc[] and .iloc[], show the first row, the second column, and a 2×2 block    from the middle of your DataFrame.

In [22]:
df = pd.DataFrame({
    "Name": ["Alice", "Bob", "Charlie", "David", "Eva"],
    "Age": [20, 21, 19, 22, 20],
    "Marks": [23, 53,23,64, 78]})
df

      Name  Age  Marks
0    Alice   20     23
1      Bob   21     53
2  Charlie   19     23
3    David   22     64
4      Eva   20     78

In [24]:
df.loc[1:2, ["Age", "Marks"]]

   Age  Marks
1   21     53
2   19     23

In [25]:
df.iloc[1:3, 1:3]

   Age  Marks
1   21     53
2   19     23

Create a 4×3 DataFrame of student names and marks. Drop one column using .drop(), drop one row by index