# Functions

In [1]:
def welcome(name = "unknown"):
    print(f"welcome {name}")

In [2]:
welcome("preta")

welcome preta

 DOC

In [ ]:
def welcome(name = "unknown"):
    
    # DOC
    
    """It is a function who welcomes the users."""
    print(f"welcome {name}")

In [5]:
help(welcome)   # showing the doc

Help on function welcome in module __main__:

welcome(name='unknown')
    It is a function who welcomes the users.

Argument

In [6]:
# dynamic variable sized argument

In [7]:
def print_num(*args):
    print(args)

In [9]:
print_num(10,20,30,121) # here I can give input to as many input i want

(10, 20, 30, 121)

As now using positional argument, we can take input of as many variable i want, so using loop I can print or use them.

In [12]:
def print_num(*args):
    for i in args:
        print(i)

In [14]:
print_num(50,23,4342,232)

50
23
4342
232

In [18]:
def numbers(a,b,c):
    print(f"a:{a}, b:{b}, c:{c}")

numbers(12,10,11)

# in here, in which serial we give input the output will shown

a:12, b:10, c:11

In [16]:
def numbers(a,b,c):
    print(f"a:{a}, b:{b}, c:{c}")

numbers(a=12, c=10, b = 11)

a:12, b:11, c:10

#### return type of a func

In [1]:
def func1(a):
    return f"Hello {a}"

print(func1("preta"))

Hello preta

Thus a function can return string

In [5]:
def func2(a,b):
    return (a,b)
# here this function will return a tuple
print(func2(2,3))

# Unzip
x,y = func2(2,3)
print(x)
print(y)

(2, 3)
2
3

# Iterators

In Python, an iterator is an object that lets you go through (iterate over) a collection of data one element at a time. List has index values, but set cann't.

In [3]:
s = [10, 20,12,321]

iterable_s = iter(s)
print(next(iterable_s))
print(next(iterable_s))
print(next(iterable_s))
print(next(iterable_s))

10
20
12
321

thus we can iterate them one by one in a list. but for a dictionary it is not serially iterated.

# Generator

Generator হলো এমন একটা বিশেষ ধরনের iterator, যা একসাথে সব ডাটা মেমোরিতে রাখে না—বরং একটা একটা করে value তৈরি করে দেয় (lazy evaluation)।

👉 এটা মূলত function দিয়েই তৈরি করা হয়, কিন্তু return এর জায়গায় yield ব্যবহার করা হয়।

In [11]:
list1 = [x for x in range(100)]  # dataset

def data_loader(chunk_size, dataset):
    for i in range(0, len(dataset), chunk_size):
        yield dataset[i:i+chunk_size]

chunked_dataset = data_loader(5,list1)

print(type(chunked_dataset))
print(next(chunked_dataset))
print(next(chunked_dataset))
print(next(chunked_dataset))

<class 'generator'>
[0, 1, 2, 3, 4]
[5, 6, 7, 8, 9]
[10, 11, 12, 13, 14]

# Some functions

In [12]:
# lambda function
import pandas as pd
df = pd.DataFrame({'Temperature(F)':[32, 56, 232, 434]})
print(df)

   Temperature(F)
0              32
1              56
2             232
3             434

Lambda function হলো Python-এর একটা ছোট, এক লাইনের anonymous function (নাম ছাড়া function)। <br>
<p>
syntax: <br>
        lambda arguments: expression </p>

In [ ]:
add = lambda a, b: a + b
# lambda arguments: expression

print(add(3, 5))  # 8

8

In [16]:
df['Temperature(C)'] = df["Temperature(F)"].apply(lambda x: (x-32)*(5/9))
df

   Temperature(F)  Temperature(C)
0              32        0.000000
1              56       13.333333
2             232      111.111111
3             434      223.333333

In [17]:
df2 = pd.DataFrame({'A': [1,2,3,4,5], 'B':[6,7,8,9,10]})
df2

   A   B
0  1   6
1  2   7
2  3   8
3  4   9
4  5  10

In [18]:
df2['root'] = df2['A'].apply(lambda x: x**(1/2))
df2

   A   B      root
0  1   6  1.000000
1  2   7  1.414214
2  3   8  1.732051
3  4   9  2.000000
4  5  10  2.236068

In [19]:
df3 = pd.DataFrame({'TK': [100,600,1000,344]})

df3['expensive'] = df3['TK'].apply(lambda x: 1 if x>500 else 0)
print(df3)

     TK  expensive
0   100          0
1   600          1
2  1000          1
3   344          0